INSERT INTO USERS (USER_NAME,EMAIL,CONTACT) VALUES('Fob','fob@uwindsor.ca','8999999999');

INSERT INTO EVENTS (EVENT_NAME,EVENT_DESCRIPTION,EVENT_DATE,EVENT_PASSCODE,EVENT_URL,EVENT_STATUS,ISDELETED,USERID) VALUES('Online Fifa','Online multiplayer fifa 2020 competition','2020-12-11','666666','fifa2020@uwindsor.ca',1, 0, IDENTITY_VAL_LOCAL());